version = "1"
agent_id = "openrouter-test"
profile = "dev"

[governance.policies]
default = "allow"

[governance.keys]
verify = "k"

[llm_profiles]
default = "or-basic"
[[llm_profiles.profiles]]
name = "or-basic"
provider = "openrouter"
model = "meta-llama/llama-3-8b-instruct"
api_key_env = "OPENROUTER_API_KEY"
