[package]
name = "acl_compiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1"
num-bigint = "0.4" # For arbitrary-precision integers
num-traits = "0.2" # Required by num-bigint
