[package]
name = "rtfs_compiler"
version = "0.1.0"
edition = "2021"

# Binary targets for different execution modes
[[bin]]
name = "rtfs_compiler"
path = "src/main.rs"

[[bin]]
name = "main_enhanced_tests"
path = "src/main_enhanced_tests.rs"

[[bin]]
name = "summary_demo"
path = "src/summary_demo.rs"

[[bin]]
name = "rtfs-repl"
path = "src/bin/rtfs_repl.rs"

[[bin]]
name = "rtfs-compiler"
path = "src/bin/rtfs_compiler.rs"

[[bin]]
name = "repl_deployment_demo"
path = "src/repl_deployment_demo.rs"

[[bin]]
name = "debug_complex_expression"
path = "debug_complex_expression.rs"

[[bin]]
name = "debug_fact_function"
path = "debug_fact_function.rs"

[[bin]]
name = "debug_simple_fn"
path = "debug_simple_fn.rs"

[[bin]]
name = "debug_environment_deep"
path = "debug_environment_deep.rs"

[[bin]]
name = "debug_closure_issue"
path = "debug_closure_issue.rs"

[[bin]]
name = "debug_env_analysis"
path = "debug_env_analysis.rs"

[[bin]]
name = "debug_simple_let"
path = "debug_simple_let.rs"

[[bin]]
name = "debug_recursive_2param"
path = "debug_recursive_2param.rs"

[[bin]]
name = "debug_test_complex_math"
path = "debug_test_complex_math.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.7"
pest_derive = "2.7"
# Command line argument parsing
clap = { version = "4.0", features = ["derive"] }
# Agent system dependencies
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.0", features = ["full"] }
uuid = { version = "1.0", features = ["v4"] }
