[package]
name = "rtfs_compiler"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <you@example.com>"]
description = "RTFS Compiler - Runtime-First Scripting Language Compiler"
license = "MIT"
repository = "https://github.com/yourusername/rtfs-compiler"

[features]
default = ["pest", "regex", "repl"]
pest = ["dep:pest"]
regex = ["dep:regex"]
repl = ["rustyline"]

[[bin]]
name = "rtfs_compiler"
path = "src/bin/rtfs_compiler.rs"

[[bin]]
name = "rtfs-repl"
path = "src/bin/rtfs_repl.rs"
required-features = ["repl"]

[dependencies]
# Parser dependencies
pest = { version = "2.7", optional = true }
pest_derive = "2.7"
regex = { version = "1.10", optional = true }

# Runtime dependencies
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
itertools = "0.12"
lazy_static = "1.4"
chrono = "0.4"
ordered-float = "3.7"
validator = { version = "0.18.1", features = ["derive"] }
schemars = "0.8.21"

# Networking/API
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.0", features = ["full"] }
uuid = { version = "1.0", features = ["v4"] }

# REPL dependencies
clap = { version = "4.0", features = ["derive"] }
rustyline = { version = "13.0", optional = true }

# Utilities
indexmap = "2.0"

[dev-dependencies]
pretty_assertions = "1.4.0"
