use std::io::Write;
use std::path::Path;
use std::process::{Command, Output, Stdio};

fn run_autonoetic(args: &[&str], stdin_input: Option<&str>) -> Output {
    let bin = env!("CARGO_BIN_EXE_autonoetic");
    let mut command = Command::new(bin);
    command.args(args);
    command.stdout(Stdio::piped());
    command.stderr(Stdio::piped());
    if stdin_input.is_some() {
        command.stdin(Stdio::piped());
    }

    let mut child = command
        .spawn()
        .expect("autonoetic test process should spawn");
    if let Some(input) = stdin_input {
        child
            .stdin
            .as_mut()
            .expect("stdin pipe should be present")
            .write_all(input.as_bytes())
            .expect("stdin should be writable");
    }
    child
        .wait_with_output()
        .expect("autonoetic test process should complete")
}

fn write_config(config_path: &Path, agents_dir: &Path) {
    let yaml = format!(
        "agents_dir: \"{}\"\nport: 4000\nofp_port: 4200\ntls: false\n",
        agents_dir.display()
    );
    std::fs::write(config_path, yaml).expect("config should write");
}

#[test]
fn test_agent_init_then_interactive_run_exits_cleanly() {
    let temp = tempfile::tempdir().expect("tempdir should create");
    let config_path = temp.path().join("config.yaml");
    let agents_dir = temp.path().join("agents");
    write_config(&config_path, &agents_dir);

    let config_arg = config_path.to_string_lossy().to_string();

    let init = run_autonoetic(
        &[
            "--config",
            config_arg.as_str(),
            "agent",
            "init",
            "agent_e2e",
            "--template",
            "coder",
        ],
        None,
    );
    assert!(
        init.status.success(),
        "agent init failed\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&init.stdout),
        String::from_utf8_lossy(&init.stderr)
    );

    let skill_path = agents_dir.join("agent_e2e").join("SKILL.md");
    let runtime_lock_path = agents_dir.join("agent_e2e").join("runtime.lock");
    assert!(skill_path.exists(), "SKILL.md should be generated by agent init");
    assert!(
        runtime_lock_path.exists(),
        "runtime.lock should be generated by agent init"
    );

    // Keep the run command hermetic: select a local provider so no API key is required.
    let skill = std::fs::read_to_string(&skill_path).expect("SKILL.md should read");
    let patched = skill.replace("provider: \"openai\"", "provider: \"ollama\"");
    std::fs::write(&skill_path, patched).expect("SKILL.md should update");

    let run = run_autonoetic(
        &[
            "--config",
            config_arg.as_str(),
            "agent",
            "run",
            "agent_e2e",
            "--interactive",
        ],
        Some("/exit\n"),
    );
    assert!(
        run.status.success(),
        "agent run failed\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&run.stdout),
        String::from_utf8_lossy(&run.stderr)
    );
    let stdout = String::from_utf8_lossy(&run.stdout);
    assert!(
        stdout.contains("Interactive mode enabled. Type /exit to quit."),
        "interactive banner should be printed, got stdout:\n{}",
        stdout
    );
}
