#!/usr/bin/env python3
"""Generate wrapper agent files from base skill + schema diff.

Inputs:
  --base-skill <path>
  --wrapper-id <id>
  --target-spec-json <json-string>
  --schema-diff-json <json-string>
  [--output-dir <path>]

Output:
  JSON object with generated file map and metadata.
  If --output-dir is provided, files are written there as well.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Dict, List


def passthrough_pre_script(notes: list[str], mappings: List[Dict[str, str]]) -> str:
    note_block = "\n".join(f"# - {n}" for n in notes)
    mapping_logic = "pass"
    if mappings:
        pairs = []
        for item in mappings:
            src = item.get("from")
            dst = item.get("to")
            if src and dst:
                pairs.append((src, dst))
        mapping_logic = "MAPPINGS = " + repr(pairs) + "\n" + """
try:
    if request.get("messages"):
        content_obj = json.loads(request["messages"][-1]["content"])
        if isinstance(content_obj, dict):
            for src, dst in MAPPINGS:
                if src in content_obj and dst not in content_obj:
                    content_obj[dst] = content_obj.pop(src)
            request["messages"][-1]["content"] = json.dumps(content_obj)
except Exception:
    pass
"""
    return f"""#!/usr/bin/env python3
import json
import sys

# Generated by agent-adapter.default.
{note_block}

request = json.load(sys.stdin)
{mapping_logic}
print(json.dumps(request))
"""


def passthrough_post_script(notes: list[str], mappings: List[Dict[str, str]]) -> str:
    note_block = "\n".join(f"# - {n}" for n in notes)
    mapping_logic = "pass"
    if mappings:
        pairs = []
        for item in mappings:
            src = item.get("to")
            dst = item.get("from")
            if src and dst:
                pairs.append((src, dst))
        mapping_logic = "MAPPINGS = " + repr(pairs) + "\n" + """
try:
    text_obj = json.loads(response.get("text", ""))
    if isinstance(text_obj, dict):
        for src, dst in MAPPINGS:
            if src in text_obj and dst not in text_obj:
                text_obj[dst] = text_obj.pop(src)
        response["text"] = json.dumps(text_obj)
except Exception:
    pass
"""
    return f"""#!/usr/bin/env python3
import json
import sys

# Generated by agent-adapter.default.
{note_block}

response = json.load(sys.stdin)
{mapping_logic}
print(json.dumps(response))
"""


def render_skill(
    wrapper_id: str,
    target_spec: Dict[str, Any],
    with_pre: bool,
    with_post: bool,
    base_skill: str,
    base_capabilities: Any | None,
) -> str:
    middleware_lines = ""
    if with_pre or with_post:
        middleware_lines = "    middleware:\n"
        if with_pre:
            middleware_lines += '      pre_process: "python3 scripts/pre_map.py"\n'
        if with_post:
            middleware_lines += '      post_process: "python3 scripts/post_map.py"\n'

    io_block = json.dumps(target_spec, indent=2)
    io_block = "\n".join("      " + line for line in io_block.splitlines())
    capabilities_block = ""
    if base_capabilities is not None:
        caps_json = json.dumps(base_capabilities, indent=2)
        caps_json = "\n".join("      " + line for line in caps_json.splitlines())
        capabilities_block = f"    capabilities:\n{caps_json}\n"

    return f"""---
name: "{wrapper_id}"
description: "Wrapper generated by agent-adapter.default"
metadata:
  autonoetic:
    version: "1.0"
    runtime:
      engine: "autonoetic"
      gateway_version: "0.1.0"
      sdk_version: "0.1.0"
      type: "stateful"
      sandbox: "bubblewrap"
      runtime_lock: "runtime.lock"
    agent:
      id: "{wrapper_id}"
      name: "{wrapper_id}"
      description: "Wrapper generated by agent-adapter.default"
{capabilities_block}    llm_config:
      provider: "openai"
      model: "gpt-4o"
      temperature: 0.0
    io:
{io_block}
{middleware_lines}---
# {wrapper_id}

This wrapper adapts I/O around a base specialist.

## Base Skill Reference (excerpt)

```text
{base_skill[:2000]}
```
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--base-skill", required=True)
    parser.add_argument("--wrapper-id", required=True)
    parser.add_argument("--target-spec-json", required=True)
    parser.add_argument("--schema-diff-json", required=True)
    parser.add_argument("--base-manifest-json")
    parser.add_argument("--output-dir")
    args = parser.parse_args()

    base_skill = Path(args.base_skill).read_text(encoding="utf-8")
    target_spec = json.loads(args.target_spec_json)
    schema_diff = json.loads(args.schema_diff_json)
    base_manifest = json.loads(args.base_manifest_json) if args.base_manifest_json else {}
    base_capabilities = base_manifest.get("capabilities")

    pre_needed = bool(schema_diff.get("requires_input_mapping"))
    post_needed = bool(schema_diff.get("requires_output_mapping"))
    notes = [str(n) for n in schema_diff.get("notes", [])]
    input_mappings = schema_diff.get("input_mappings") or []
    output_mappings = schema_diff.get("output_mappings") or []

    files: Dict[str, str] = {}
    files["SKILL.md"] = render_skill(
        args.wrapper_id,
        target_spec,
        with_pre=pre_needed,
        with_post=post_needed,
        base_skill=base_skill,
        base_capabilities=base_capabilities,
    )
    files["runtime.lock"] = (
        "gateway:\n"
        '  artifact: "marketplace://gateway/autonoetic-gateway"\n'
        '  version: "0.1.0"\n'
        '  sha256: "replace-me"\n'
        "sdk:\n"
        '  version: "0.1.0"\n'
        "sandbox:\n"
        '  backend: "bubblewrap"\n'
        "dependencies: []\n"
        "artifacts: []\n"
    )
    if pre_needed:
        files["scripts/pre_map.py"] = passthrough_pre_script(notes, input_mappings)
    if post_needed:
        files["scripts/post_map.py"] = passthrough_post_script(notes, output_mappings)

    if args.output_dir:
        out_dir = Path(args.output_dir)
        for rel_path, content in files.items():
            target = out_dir / rel_path
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8")

    print(
        json.dumps(
            {
                "wrapper_id": args.wrapper_id,
                "requires_input_mapping": pre_needed,
                "requires_output_mapping": post_needed,
                "files": list(files.keys()),
            }
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
